version: '3.8'
services:
  guiaseg:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: backdocker  
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://basedocker:5432/baseaseg
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: hola
      ports:
        - "9898:8080"
      depends_on:
        - postgres

  postgres:
    image: postgres:15
    container_name: basedocker
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hola
      POSTGRES_DB: baseaseg
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  postgres_data:
