version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: basedocker
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: baseaseg
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  guiaseg:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backdocker  
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/baseaseg 
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
    ports:
      - "9898:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
